# Generated by Django 4.0.3 on 2022-04-25 03:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0003_review_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='review',
            name='privacy',
            field=models.CharField(choices=[('Public', 'Public'), ('Friends only', 'Friends only'), ('Anonymous', 'Anonymous')], default='Public', max_length=50),
        ),
        migrations.AlterField(
            model_name='review',
            name='rating',
            field=models.IntegerField(),
        ),
        migrations.AddConstraint(
            model_name='review',
            constraint=models.CheckConstraint(check=models.Q(('rating__gte', 1), ('rating__lte', 5)), name='A rating is valid between 1 and 5'),
        ),
    ]
