# Generated by Django 4.0.3 on 2022-04-25 03:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0004_review_privacy_alter_review_rating_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='review',
            name='spoilers',
            field=models.BooleanField(default=False),
        ),
    ]
